<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>ETAB.Engineering.Service</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\ETAB.Engineering.Core\ETAB.Engineering.Core.csproj" />
  </ItemGroup>
</Project>
