using System.Security;
using System.Text;
using ETAB.Engineering.Core.Model;

namespace ETAB.Engineering.Core.Generation;

internal static class TwinCatRuntimeRenderer
{
    public static string Render(
        string programName,
        string gvlName,
        string projectPrefix,
        string sourceId,
        Guid twinCatGuid,
        string productVersion,
        IReadOnlyList<EtabNode> nodes,
        bool callRelationWiring)
    {
        var declaration = new StringBuilder();
        declaration.AppendLine(
            $"(* <auto-generated by ETAB Engineering; source-id: {sourceId}; artifact-kind: program-call-structure> *)");
        declaration.AppendLine($"PROGRAM {programName}");

        var runtimeVariables = new List<string>();
        foreach (var node in nodes)
        {
            switch (node.Kind)
            {
                case "applicationUnit":
                    runtimeVariables.Add(
                        $"e{node.Name}EtabCommand : ETAB.E_ETAB_UnitCommand;");
                    runtimeVariables.Add(
                        $"st{node.Name}Options : ETAB.ST_ETAB_ApplicationUnitOptions;");
                    break;
                case "commandUnit":
                    runtimeVariables.Add(
                        $"e{node.Name}EtabCommand : ETAB.E_ETAB_UnitCommand;");
                    runtimeVariables.Add(
                        $"st{node.Name}Options : ETAB.ST_ETAB_CommandOptions;");
                    break;
                case "recipeManager":
                    runtimeVariables.Add(
                        $"st{node.Name}Options : ETAB.ST_ETAB_RecipeOptions;");
                    break;
                case "machineLink":
                    if (!node.Generate.RequestType)
                    {
                        runtimeVariables.Add(
                            $"st{node.Name}Rx : ETAB.ST_ETAB_MachineLinkData;");
                    }
                    runtimeVariables.Add(
                        $"st{node.Name}Options : ETAB.ST_ETAB_MachineLinkOptions;");
                    break;
            }
        }
        if (runtimeVariables.Count > 0)
        {
            declaration.AppendLine("VAR");
            foreach (var variable in runtimeVariables)
            {
                declaration.AppendLine($"    {variable}");
            }
            declaration.AppendLine("END_VAR");
        }

        var implementation = new StringBuilder();
        implementation.AppendLine(
            "(* Generated runtime binding: request -> ETAB FB -> project status. *)");
        if (callRelationWiring)
        {
            implementation.AppendLine($"{gvlName}.fbEtabRelationWiring();");
            implementation.AppendLine();
        }

        foreach (var node in nodes)
        {
            AppendNodeCall(implementation, gvlName, projectPrefix, node);
            implementation.AppendLine();
        }

        var escapedName = SecurityElement.Escape(programName);
        var escapedVersion = SecurityElement.Escape(productVersion);
        var xml = new StringBuilder();
        xml.Append("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n");
        xml.Append($"<TcPlcObject Version=\"1.1.0.1\" ProductVersion=\"{escapedVersion}\">\n");
        xml.Append($"  <POU Name=\"{escapedName}\" Id=\"{{{twinCatGuid:D}}}\" SpecialFunc=\"None\">\n");
        xml.Append($"    <Declaration><![CDATA[{EscapeCData(declaration.ToString())}]]></Declaration>\n");
        xml.Append("    <Implementation>\n");
        xml.Append($"      <ST><![CDATA[{EscapeCData(implementation.ToString())}]]></ST>\n");
        xml.Append("    </Implementation>\n");
        xml.Append("  </POU>\n");
        xml.Append("</TcPlcObject>\n");
        return NormalizeLineEndings(xml.ToString());
    }

    private static void AppendNodeCall(
        StringBuilder implementation,
        string gvlName,
        string projectPrefix,
        EtabNode node)
    {
        implementation.AppendLine($"(* {node.Kind}: {node.Name} *)");
        switch (node.Kind)
        {
            case "applicationUnit":
                AppendUnitCommandMapping(implementation, gvlName, projectPrefix, node);
                AppendApplicationUnitCall(implementation, gvlName, projectPrefix, node);
                break;
            case "commandUnit":
                AppendUnitCommandMapping(implementation, gvlName, projectPrefix, node);
                AppendCommandUnitCall(implementation, gvlName, projectPrefix, node);
                break;
            case "recipeManager":
                AppendRecipeManagerCall(implementation, gvlName, projectPrefix, node);
                break;
            case "machineLink":
                AppendMachineLinkCall(implementation, gvlName, projectPrefix, node);
                break;
            default:
                throw new InvalidOperationException($"Unsupported runtime node kind '{node.Kind}'.");
        }
    }

    private static void AppendUnitCommandMapping(
        StringBuilder implementation,
        string gvlName,
        string projectPrefix,
        EtabNode node)
    {
        var mappedVariable = $"e{node.Name}EtabCommand";
        if (!node.Generate.RequestType || !node.Generate.CommandEnum)
        {
            implementation.AppendLine(
                $"{mappedVariable} := ETAB.E_ETAB_UnitCommand.NoAction;");
            return;
        }

        var request = $"{gvlName}.st{node.Name}Request";
        var commandType = $"E_{projectPrefix}_{node.SymbolStem}Command";
        implementation.AppendLine($"CASE {request}.eCommand OF");
        foreach (var command in node.Commands
                     .OrderBy(command => command.EnumValue)
                     .ThenBy(command => command.Name, StringComparer.Ordinal)
                     .ThenBy(command => command.Id, StringComparer.Ordinal))
        {
            implementation.AppendLine(
                $"    {commandType}.{command.Name}: " +
                $"{mappedVariable} := ETAB.E_ETAB_UnitCommand.{command.EtabCommandMapping};");
        }
        implementation.AppendLine("ELSE");
        implementation.AppendLine(
            $"    {mappedVariable} := ETAB.E_ETAB_UnitCommand.NoAction;");
        implementation.AppendLine("END_CASE");
    }

    private static void AppendApplicationUnitCall(
        StringBuilder implementation,
        string gvlName,
        string projectPrefix,
        EtabNode node)
    {
        var request = node.Generate.RequestType && node.Generate.CommandEnum
            ? $"{gvlName}.st{node.Name}Request"
            : null;
        var settings = node.ApplicationUnit
            ?? throw new InvalidOperationException(
                $"ApplicationUnit settings are missing for '{node.Name}'.");
        var options = $"st{node.Name}Options";
        implementation.AppendLine(
            $"{options}.stCommandOptions.nStartState := {settings.Command.StartState};");
        implementation.AppendLine(
            $"{options}.stCommandOptions.bResetErrorOnStart := {Bool(settings.Command.ResetErrorOnStart)};");
        implementation.AppendLine($"{options}.eStartMode := {Mode(settings.StartMode)};");
        implementation.AppendLine($"{options}.eHomingMode := {Mode(settings.HomingMode)};");
        implementation.AppendLine($"{options}.eStopMode := {Mode(settings.StopMode)};");
        implementation.AppendLine(
            $"{options}.bKeepRemoteControl := {Bool(settings.KeepRemoteControl)};");
        implementation.AppendLine(
            $"{options}.bSetMachineErrorOnCommandError := {Bool(settings.SetMachineErrorOnCommandError)};");
        implementation.AppendLine($"{gvlName}.fb{node.Name}(");
        implementation.AppendLine($"    bExecute := {(request is null ? "FALSE" : $"{request}.bExecute")},");
        implementation.AppendLine($"    eCommand := e{node.Name}EtabCommand,");
        implementation.AppendLine($"    nCommandID := {(request is null ? "0" : $"{request}.nCommandID")},");
        implementation.AppendLine("    bEnable := TRUE,");
        implementation.AppendLine($"    stOptions := {options});");

        if (node.Generate.StatusType)
        {
            var status = $"{gvlName}.st{node.Name}Status";
            implementation.AppendLine($"{status}.stUnit := {gvlName}.fb{node.Name}.stStatus;");
            if (node.Commands.Count > 0)
            {
                implementation.AppendLine(
                    $"{status}.stOperation := {gvlName}.fb{node.Name}.refStatus;");
            }
        }
    }

    private static void AppendCommandUnitCall(
        StringBuilder implementation,
        string gvlName,
        string projectPrefix,
        EtabNode node)
    {
        var request = node.Generate.RequestType && node.Generate.CommandEnum
            ? $"{gvlName}.st{node.Name}Request"
            : null;
        var settings = node.CommandUnit
            ?? throw new InvalidOperationException(
                $"CommandUnit settings are missing for '{node.Name}'.");
        var options = $"st{node.Name}Options";
        implementation.AppendLine($"{options}.nStartState := {settings.StartState};");
        implementation.AppendLine(
            $"{options}.bResetErrorOnStart := {Bool(settings.ResetErrorOnStart)};");
        implementation.AppendLine($"{gvlName}.fb{node.Name}(");
        implementation.AppendLine($"    bExecute := {(request is null ? "FALSE" : $"{request}.bExecute")},");
        implementation.AppendLine($"    eCommand := e{node.Name}EtabCommand,");
        implementation.AppendLine($"    nCommandID := {(request is null ? "0" : $"{request}.nCommandID")},");
        implementation.AppendLine("    bEnable := TRUE,");
        implementation.AppendLine($"    stOptions := {options});");

        if (node.Generate.StatusType)
        {
            implementation.AppendLine(
                $"{gvlName}.st{node.Name}Status.stCommand := {gvlName}.fb{node.Name}.stStatus;");
        }
    }

    private static void AppendRecipeManagerCall(
        StringBuilder implementation,
        string gvlName,
        string projectPrefix,
        EtabNode node)
    {
        var settings = node.RecipeManager
            ?? throw new InvalidOperationException(
                $"RecipeManager settings are missing for '{node.Name}'.");
        var request = node.Generate.RequestType
            ? $"{gvlName}.st{node.Name}Request"
            : null;
        var data = request is null ? null : $"{gvlName}.st{node.Name}Data";
        var defaults = request is null ? null : $"{gvlName}.st{node.Name}DefaultData";
        var options = $"st{node.Name}Options";
        implementation.AppendLine(
            $"{options}.bEnableAutoSave := {Bool(settings.EnableAutoSave)};");
        implementation.AppendLine(
            $"{options}.bEnableBackupFile := {Bool(settings.EnableBackupFile)};");
        implementation.AppendLine(
            $"{options}.bRequireExternalValidation := {Bool(settings.RequireExternalValidation)};");
        implementation.AppendLine($"{gvlName}.fb{node.Name}(");
        implementation.AppendLine($"    bExecute := {(request is null ? "FALSE" : $"{request}.bExecute")},");
        implementation.AppendLine(
            $"    eCommand := {(request is null ? "ETAB.E_ETAB_RecipeCommand.NoAction" : $"{request}.eCommand")},");
        implementation.AppendLine($"    pData := {(data is null ? "0" : $"ADR({data})")},");
        implementation.AppendLine($"    nDataSize := {(data is null ? "0" : $"SIZEOF({data})")},");
        implementation.AppendLine($"    pDefaultData := {(defaults is null ? "0" : $"ADR({defaults})")},");
        implementation.AppendLine($"    nDefaultDataSize := {(defaults is null ? "0" : $"SIZEOF({defaults})")},");
        implementation.AppendLine(
            $"    bExternalValid := {(request is null ? "TRUE" : $"{request}.bExternalValid")},");
        implementation.AppendLine($"    stOptions := {options},");
        implementation.AppendLine($"    sFilePath := '{StringLiteral(settings.FilePath)}',");
        implementation.AppendLine($"    sFileName := '{StringLiteral(settings.FileName)}',");
        implementation.AppendLine(
            $"    sSaveAsFileName := {(request is null ? "''" : $"{request}.sSaveAsFileName")},");
        implementation.AppendLine($"    sXPath := '{StringLiteral(settings.XPath)}');");

        if (node.Generate.StatusType)
        {
            implementation.AppendLine(
                $"{gvlName}.st{node.Name}Status.stRecipe := {gvlName}.fb{node.Name}.stStatus;");
        }
    }

    private static void AppendMachineLinkCall(
        StringBuilder implementation,
        string gvlName,
        string projectPrefix,
        EtabNode node)
    {
        var settings = node.MachineLink
            ?? throw new InvalidOperationException(
                $"MachineLink settings are missing for '{node.Name}'.");
        var request = node.Generate.RequestType
            ? $"{gvlName}.st{node.Name}Request"
            : null;
        string Input(string member, string fallback) =>
            request is null ? fallback : $"{request}.{member}";

        var options = $"st{node.Name}Options";
        implementation.AppendLine(
            $"{options}.eBridgeType := ETAB.E_ETAB_MachineLinkBridgeType.{settings.BridgeType};");
        implementation.AppendLine($"{options}.tWatchdogTime := {settings.WatchdogTime};");
        implementation.AppendLine(
            $"{options}.bPrimaryWinsTie := {Bool(settings.PrimaryWinsTie)};");
        implementation.AppendLine(
            $"{options}.bAllowTokenWithoutPartnerAlive := {Bool(settings.AllowTokenWithoutPartnerAlive)};");
        implementation.AppendLine(
            $"{options}.bClearTxWhenDisabled := {Bool(settings.ClearTxWhenDisabled)};");
        var rx = request is null
            ? $"st{node.Name}Rx"
            : $"{request}.stRx";
        if (request is null)
        {
            implementation.AppendLine($"{rx}.nHeartbeat := 0;");
            implementation.AppendLine($"{rx}.bReqToken := FALSE;");
            implementation.AppendLine($"{rx}.bTokenGranted := FALSE;");
            implementation.AppendLine($"{rx}.bBusy := FALSE;");
            implementation.AppendLine($"{rx}.bError := FALSE;");
            implementation.AppendLine($"{rx}.nState := 0;");
        }
        implementation.AppendLine($"{gvlName}.fb{node.Name}(");
        implementation.AppendLine($"    bEnable := {Input("bEnable", "TRUE")},");
        implementation.AppendLine($"    bIsPrimary := {Bool(settings.IsPrimary)},");
        implementation.AppendLine($"    bLocalReqToken := {Input("bLocalReqToken", "FALSE")},");
        implementation.AppendLine($"    bLocalBusy := {Input("bLocalBusy", "FALSE")},");
        implementation.AppendLine($"    bLocalError := {Input("bLocalError", "FALSE")},");
        implementation.AppendLine($"    nLocalState := {Input("nLocalState", "0")},");
        implementation.AppendLine($"    stRx := {rx},");
        implementation.AppendLine($"    bBridgeOk := {Input("bBridgeOk", "TRUE")},");
        implementation.AppendLine($"    stOptions := {options});");
        implementation.AppendLine(
            $"{gvlName}.st{node.Name}Tx := {gvlName}.fb{node.Name}.stTx;");

        if (node.Generate.StatusType)
        {
            implementation.AppendLine(
                $"{gvlName}.st{node.Name}Status.stLink := {gvlName}.fb{node.Name}.stStatus;");
        }
    }

    private static string Mode(string value) =>
        value.StartsWith("ET.eMODE.", StringComparison.Ordinal)
            ? value
            : $"ET.eMODE.{value}";

    private static string Bool(bool value) => value ? "TRUE" : "FALSE";

    private static string StringLiteral(string value) =>
        value.Replace("'", "''", StringComparison.Ordinal);

    private static string EscapeCData(string value) =>
        value.Replace("]]>", "]]]]><![CDATA[>", StringComparison.Ordinal);

    private static string NormalizeLineEndings(string value) =>
        value.Replace("\r\n", "\n", StringComparison.Ordinal)
            .Replace('\r', '\n');
}
