using System.Security;
using System.Text;

namespace ETAB.Engineering.Core.Generation;

internal sealed record GeneratedCommandRoute(
    string SourceCommandName,
    string TargetCommandName);

internal sealed record GeneratedRelationBinding(
    string RelationId,
    string Kind,
    string SourceName,
    string TargetName,
    string MemberName,
    string SourceInstanceName,
    string TargetInstanceName,
    string SourceKind,
    string TargetKind,
    string TargetStatusMember,
    string? SourceCommandType,
    string? SourceRequestVariable,
    string? TargetCommandType,
    string? TargetRequestType,
    string? TargetRequestVariable,
    string? TargetStatusType,
    string? TargetStatusVariable,
    string? TargetStatusValueMember,
    IReadOnlyList<GeneratedCommandRoute> CommandRoutes,
    Guid MemberGuid);

internal static class TwinCatRelationRenderer
{
    public static string Render(
        string functionBlockName,
        string gvlName,
        string sourceId,
        Guid twinCatGuid,
        string productVersion,
        IReadOnlyList<GeneratedRelationBinding> bindings)
    {
        var declaration =
            $"(* <auto-generated by ETAB Engineering; source-id: {sourceId}; artifact-kind: relation-wiring> *)\n" +
            $"FUNCTION_BLOCK {functionBlockName}\n";
        var implementation = RenderCyclicImplementation(gvlName, bindings);

        var escapedName = SecurityElement.Escape(functionBlockName);
        var escapedVersion = SecurityElement.Escape(productVersion);
        var xml = new StringBuilder();
        xml.Append("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n");
        xml.Append($"<TcPlcObject Version=\"1.1.0.1\" ProductVersion=\"{escapedVersion}\">\n");
        xml.Append($"  <POU Name=\"{escapedName}\" Id=\"{{{twinCatGuid:D}}}\" SpecialFunc=\"None\">\n");
        xml.Append($"    <Declaration><![CDATA[{EscapeCData(declaration)}]]></Declaration>\n");
        xml.Append("    <Implementation>\n");
        xml.Append($"      <ST><![CDATA[{EscapeCData(implementation)}]]></ST>\n");
        xml.Append("    </Implementation>\n");

        foreach (var binding in bindings.Where(item => item.Kind != "contains"))
        {
            AppendMember(xml, gvlName, binding);
        }

        xml.Append("  </POU>\n");
        xml.Append("</TcPlcObject>\n");
        return NormalizeLineEndings(xml.ToString());
    }

    private static string RenderCyclicImplementation(
        string gvlName,
        IReadOnlyList<GeneratedRelationBinding> bindings)
    {
        var implementation = new StringBuilder();
        var containsBindings = bindings.Where(item => item.Kind == "contains").ToArray();
        var hasCyclicAssignment = false;
        foreach (var binding in containsBindings)
        {
            if (binding.SourceKind == "applicationUnit" &&
                binding.TargetKind == "applicationUnit")
            {
                hasCyclicAssignment = true;
                implementation.AppendLine(
                    $"(* contains: {binding.SourceName} -> {binding.TargetName} *)");
                implementation.AppendLine(
                    $"{gvlName}.{binding.TargetInstanceName}.rUnit.ipMasterUnit := " +
                    $"{gvlName}.{binding.SourceInstanceName}.rUnit;");
            }
            else
            {
                implementation.AppendLine(
                    $"(* contains: {binding.SourceName} -> {binding.TargetName} is structural only; " +
                    "Command Units have no ET state-model parent reference. *)");
            }
        }


        foreach (var binding in bindings.Where(
                     item => item.Kind == "commands" && item.CommandRoutes.Count > 0))
        {
            if (binding.SourceCommandType is null ||
                binding.SourceRequestVariable is null ||
                binding.TargetCommandType is null ||
                binding.TargetRequestType is null ||
                binding.TargetRequestVariable is null)
            {
                continue;
            }

            hasCyclicAssignment = true;
            var sourceRequest = $"{gvlName}.{binding.SourceRequestVariable}";
            var targetRequest = $"{gvlName}.{binding.TargetRequestVariable}";
            implementation.AppendLine(
                $"(* command routes: {binding.SourceName} -> {binding.TargetName} *)");
            implementation.AppendLine($"IF {sourceRequest}.bExecute THEN");
            implementation.AppendLine($"    CASE {sourceRequest}.eCommand OF");
            foreach (var route in binding.CommandRoutes)
            {
                implementation.AppendLine(
                    $"        {binding.SourceCommandType}.{route.SourceCommandName}:");
                implementation.AppendLine($"            {targetRequest}.bExecute := TRUE;");
                implementation.AppendLine(
                    $"            {targetRequest}.eCommand := " +
                    $"{binding.TargetCommandType}.{route.TargetCommandName};");
                implementation.AppendLine(
                    $"            {targetRequest}.nCommandID := {sourceRequest}.nCommandID;");
            }
            implementation.AppendLine("    ELSE");
            implementation.AppendLine($"        {targetRequest}.bExecute := FALSE;");
            implementation.AppendLine("    END_CASE");
            implementation.AppendLine("ELSE");
            implementation.AppendLine($"    {targetRequest}.bExecute := FALSE;");
            implementation.AppendLine("END_IF");
        }

        if (!hasCyclicAssignment)
        {
            implementation.AppendLine(
                ";(* Relation adapters are invoked explicitly through their generated methods. *)");
        }

        return implementation.ToString();
    }

    private static void AppendMember(
        StringBuilder xml,
        string gvlName,
        GeneratedRelationBinding binding)
    {
        var declaration = binding.Kind switch
        {
            "commands" when binding.TargetRequestType is not null =>
                $"METHOD PUBLIC {binding.MemberName} : BOOL\n" +
                "VAR_INPUT\n" +
                $"    stRequest : {binding.TargetRequestType};\n" +
                "END_VAR\n",
            "commands" =>
                $"METHOD PUBLIC {binding.MemberName} : BOOL\n" +
                "VAR_INPUT\n" +
                "    bExecute : BOOL;\n" +
                "    eCommand : ETAB.E_ETAB_UnitCommand;\n" +
                "    nCommandID : UDINT;\n" +
                "END_VAR\n",
            "observes" =>
                $"METHOD PUBLIC {binding.MemberName} : {ResolvedStatusType(binding)}\n" +
                "VAR_INPUT\n" +
                "END_VAR\n",
            "usesRecipe" =>
                $"METHOD PUBLIC {binding.MemberName} : {ResolvedStatusType(binding)}\n" +
                "VAR_INPUT\n" +
                "END_VAR\n",
            "usesLink" =>
                $"METHOD PUBLIC {binding.MemberName} : {ResolvedStatusType(binding)}\n" +
                "VAR_INPUT\n" +
                "END_VAR\n",
            _ => throw new InvalidOperationException(
                $"Unsupported generated relation kind '{binding.Kind}'.")
        };
        var implementation = binding.Kind switch
        {
            "commands" when binding.TargetRequestVariable is not null =>
                $"{gvlName}.{binding.TargetRequestVariable} := stRequest;\n" +
                $"{binding.MemberName} := {CommandBusyExpression(gvlName, binding)};\n",
            "commands" =>
                $"{binding.MemberName} := {gvlName}.{binding.TargetInstanceName}.StartCommand(\n" +
                "    bExecute := bExecute,\n" +
                "    eCommand := eCommand,\n" +
                "    nCommandID := nCommandID);\n",
            "observes" when binding.TargetStatusVariable is not null =>
                $"{binding.MemberName} := {gvlName}.{binding.TargetStatusVariable};\n",
            "observes" =>
                $"{binding.MemberName} := {gvlName}.{binding.TargetInstanceName}." +
                $"{binding.TargetStatusMember};\n",
            "usesRecipe" or "usesLink" when binding.TargetStatusVariable is not null =>
                $"{binding.MemberName} := {gvlName}.{binding.TargetStatusVariable};\n",
            "usesRecipe" or "usesLink" =>
                $"{binding.MemberName} := {gvlName}.{binding.TargetInstanceName}." +
                $"{binding.TargetStatusMember};\n",
            _ => throw new InvalidOperationException(
                $"Unsupported generated relation kind '{binding.Kind}'.")
        };

        var escapedMemberName = SecurityElement.Escape(binding.MemberName);
        xml.Append($"    <Method Name=\"{escapedMemberName}\" Id=\"{{{binding.MemberGuid:D}}}\">\n");
        xml.Append($"      <Declaration><![CDATA[{EscapeCData(declaration)}]]></Declaration>\n");
        xml.Append("      <Implementation>\n");
        xml.Append($"        <ST><![CDATA[{EscapeCData(implementation)}]]></ST>\n");
        xml.Append("      </Implementation>\n");
        xml.Append("    </Method>\n");
    }

    private static string ResolvedStatusType(GeneratedRelationBinding binding) =>
        binding.TargetStatusType ?? binding.TargetKind switch
        {
            "applicationUnit" => "ETAB.ST_ETAB_ApplicationUnitStatus",
            "commandUnit" => "ETAB.ST_ETAB_CommandStatus",
            "recipeManager" => "ETAB.ST_ETAB_RecipeStatus",
            "machineLink" => "ETAB.ST_ETAB_MachineLinkStatus",
            _ => throw new InvalidOperationException(
                $"Unsupported relation status kind '{binding.TargetKind}'.")
        };

    private static string CommandBusyExpression(
        string gvlName,
        GeneratedRelationBinding binding)
    {
        if (binding.TargetStatusVariable is not null &&
            binding.TargetStatusValueMember is not null)
        {
            return $"{gvlName}.{binding.TargetStatusVariable}." +
                   $"{binding.TargetStatusValueMember}.bBusy";
        }

        return $"{gvlName}.{binding.TargetInstanceName}.refStatus.bBusy";
    }

    private static string EscapeCData(string value) =>
        value.Replace("]]>", "]]]]><![CDATA[>", StringComparison.Ordinal);

    private static string NormalizeLineEndings(string value) =>
        value.Replace("\r\n", "\n", StringComparison.Ordinal)
            .Replace('\r', '\n');
}
