using System.Security;
using System.Text;

namespace ETAB.Engineering.Core.Generation;

internal sealed record GeneratedRelationBinding(
    string RelationId,
    string Kind,
    string SourceName,
    string TargetName,
    string MemberName,
    string SourceInstanceName,
    string TargetInstanceName,
    string TargetKind,
    string TargetStatusMember,
    Guid MemberGuid);

internal static class TwinCatRelationRenderer
{
    public static string Render(
        string functionBlockName,
        string gvlName,
        string sourceId,
        Guid twinCatGuid,
        string productVersion,
        IReadOnlyList<GeneratedRelationBinding> bindings)
    {
        var declaration =
            $"(* <auto-generated by ETAB Engineering; source-id: {sourceId}; artifact-kind: relation-wiring> *)\n" +
            $"FUNCTION_BLOCK {functionBlockName}\n";
        var implementation = RenderCyclicImplementation(gvlName, bindings);

        var escapedName = SecurityElement.Escape(functionBlockName);
        var escapedVersion = SecurityElement.Escape(productVersion);
        var xml = new StringBuilder();
        xml.Append("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n");
        xml.Append($"<TcPlcObject Version=\"1.1.0.1\" ProductVersion=\"{escapedVersion}\">\n");
        xml.Append($"  <POU Name=\"{escapedName}\" Id=\"{{{twinCatGuid:D}}}\" SpecialFunc=\"None\">\n");
        xml.Append($"    <Declaration><![CDATA[{EscapeCData(declaration)}]]></Declaration>\n");
        xml.Append("    <Implementation>\n");
        xml.Append($"      <ST><![CDATA[{EscapeCData(implementation)}]]></ST>\n");
        xml.Append("    </Implementation>\n");

        foreach (var binding in bindings.Where(item => item.Kind != "contains"))
        {
            AppendMember(xml, gvlName, binding);
        }

        xml.Append("  </POU>\n");
        xml.Append("</TcPlcObject>\n");
        return NormalizeLineEndings(xml.ToString());
    }

    private static string RenderCyclicImplementation(
        string gvlName,
        IReadOnlyList<GeneratedRelationBinding> bindings)
    {
        var implementation = new StringBuilder();
        var containsBindings = bindings.Where(item => item.Kind == "contains").ToArray();
        var hasCyclicAssignment = false;
        foreach (var binding in containsBindings)
        {
            if (binding.TargetKind == "applicationUnit")
            {
                hasCyclicAssignment = true;
                implementation.AppendLine(
                    $"(* contains: {binding.SourceName} -> {binding.TargetName} *)");
                implementation.AppendLine(
                    $"{gvlName}.{binding.TargetInstanceName}.rUnit.ipMasterUnit := " +
                    $"{gvlName}.{binding.SourceInstanceName}.rUnit;");
            }
            else
            {
                implementation.AppendLine(
                    $"(* contains: {binding.SourceName} -> {binding.TargetName} is structural only; " +
                    "Command Units have no ET state-model parent reference. *)");
            }
        }

        if (!hasCyclicAssignment)
        {
            implementation.AppendLine(
                ";(* Relation adapters are invoked explicitly through their generated methods. *)");
        }

        return implementation.ToString();
    }

    private static void AppendMember(
        StringBuilder xml,
        string gvlName,
        GeneratedRelationBinding binding)
    {
        var declaration = binding.Kind switch
        {
            "commands" =>
                $"METHOD PUBLIC {binding.MemberName} : BOOL\n" +
                "VAR_INPUT\n" +
                "    bExecute : BOOL;\n" +
                "    eCommand : ETAB.E_ETAB_UnitCommand;\n" +
                "    nCommandID : UDINT;\n" +
                "END_VAR\n",
            "observes" =>
                $"METHOD PUBLIC {binding.MemberName} : {StatusType(binding)}\n" +
                "VAR_INPUT\n" +
                "END_VAR\n",
            "usesRecipe" =>
                $"METHOD PUBLIC {binding.MemberName} : ETAB.ST_ETAB_RecipeStatus\n" +
                "VAR_INPUT\n" +
                "END_VAR\n",
            "usesLink" =>
                $"METHOD PUBLIC {binding.MemberName} : ETAB.ST_ETAB_MachineLinkStatus\n" +
                "VAR_INPUT\n" +
                "END_VAR\n",
            _ => throw new InvalidOperationException(
                $"Unsupported generated relation kind '{binding.Kind}'.")
        };
        var implementation = binding.Kind switch
        {
            "commands" =>
                $"{binding.MemberName} := {gvlName}.{binding.TargetInstanceName}.StartCommand(\n" +
                "    bExecute := bExecute,\n" +
                "    eCommand := eCommand,\n" +
                "    nCommandID := nCommandID);\n",
            "observes" =>
                $"{binding.MemberName} := {gvlName}.{binding.TargetInstanceName}." +
                $"{binding.TargetStatusMember};\n",
            "usesRecipe" or "usesLink" =>
                $"{binding.MemberName} := {gvlName}.{binding.TargetInstanceName}." +
                $"{binding.TargetStatusMember};\n",
            _ => throw new InvalidOperationException(
                $"Unsupported generated relation kind '{binding.Kind}'.")
        };

        var escapedMemberName = SecurityElement.Escape(binding.MemberName);
        xml.Append($"    <Method Name=\"{escapedMemberName}\" Id=\"{{{binding.MemberGuid:D}}}\">\n");
        xml.Append($"      <Declaration><![CDATA[{EscapeCData(declaration)}]]></Declaration>\n");
        xml.Append("      <Implementation>\n");
        xml.Append($"        <ST><![CDATA[{EscapeCData(implementation)}]]></ST>\n");
        xml.Append("      </Implementation>\n");
        xml.Append("    </Method>\n");
    }

    private static string StatusType(GeneratedRelationBinding binding) =>
        binding.TargetKind == "applicationUnit"
            ? "ETAB.ST_ETAB_ApplicationUnitStatus"
            : "ETAB.ST_ETAB_CommandStatus";

    private static string EscapeCData(string value) =>
        value.Replace("]]>", "]]]]><![CDATA[>", StringComparison.Ordinal);

    private static string NormalizeLineEndings(string value) =>
        value.Replace("\r\n", "\n", StringComparison.Ordinal)
            .Replace('\r', '\n');
}
