using System.Security;
using System.Text;

namespace ETAB.Engineering.Core.Generation;

internal sealed record GeneratedInstance(string Name, string TypeName);

internal static class TwinCatGvlRenderer
{
    public static string RenderInstances(
        string gvlName,
        string sourceId,
        Guid twinCatGuid,
        string productVersion,
        IReadOnlyList<GeneratedInstance> instances)
    {
        var declaration = new StringBuilder();
        declaration.AppendLine(
            $"(* <auto-generated by ETAB Engineering; source-id: {sourceId}; artifact-kind: instance-gvl> *)");
        declaration.AppendLine("{attribute 'qualified_only'}");
        declaration.AppendLine("VAR_GLOBAL");
        foreach (var instance in instances)
        {
            declaration.AppendLine($"    {instance.Name} : {instance.TypeName};");
        }
        declaration.AppendLine("END_VAR");

        var escapedName = SecurityElement.Escape(gvlName);
        var escapedVersion = SecurityElement.Escape(productVersion);
        var xml = new StringBuilder();
        xml.Append("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n");
        xml.Append($"<TcPlcObject Version=\"1.1.0.1\" ProductVersion=\"{escapedVersion}\">\n");
        xml.Append($"  <GVL Name=\"{escapedName}\" Id=\"{{{twinCatGuid:D}}}\">\n");
        xml.Append($"    <Declaration><![CDATA[{EscapeCData(declaration.ToString())}]]></Declaration>\n");
        xml.Append("  </GVL>\n");
        xml.Append("</TcPlcObject>\n");
        return NormalizeLineEndings(xml.ToString());
    }

    private static string EscapeCData(string value) =>
        value.Replace("]]>", "]]]]><![CDATA[>", StringComparison.Ordinal);

    private static string NormalizeLineEndings(string value) =>
        value.Replace("\r\n", "\n", StringComparison.Ordinal)
            .Replace('\r', '\n');
}
