using System.Security;
using System.Text;

namespace ETAB.Engineering.Core.Generation;

internal static class TwinCatPouRenderer
{
    public static string RenderProgramCallStructure(
        string programName,
        string gvlName,
        string sourceId,
        Guid twinCatGuid,
        string productVersion,
        IReadOnlyList<GeneratedInstance> instances)
    {
        var declaration =
            $"(* <auto-generated by ETAB Engineering; source-id: {sourceId}; artifact-kind: program-call-structure> *)\n" +
            $"PROGRAM {programName}\n";
        var implementation = new StringBuilder();
        implementation.AppendLine(
            "(* Calls generated instances once per cycle. Custom types must not require VAR_IN_OUT call arguments. *)");
        foreach (var instance in instances)
        {
            implementation.AppendLine($"{gvlName}.{instance.Name}();");
        }

        var escapedName = SecurityElement.Escape(programName);
        var escapedVersion = SecurityElement.Escape(productVersion);
        var xml = new StringBuilder();
        xml.Append("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n");
        xml.Append($"<TcPlcObject Version=\"1.1.0.1\" ProductVersion=\"{escapedVersion}\">\n");
        xml.Append($"  <POU Name=\"{escapedName}\" Id=\"{{{twinCatGuid:D}}}\" SpecialFunc=\"None\">\n");
        xml.Append($"    <Declaration><![CDATA[{EscapeCData(declaration)}]]></Declaration>\n");
        xml.Append("    <Implementation>\n");
        xml.Append($"      <ST><![CDATA[{EscapeCData(implementation.ToString())}]]></ST>\n");
        xml.Append("    </Implementation>\n");
        xml.Append("  </POU>\n");
        xml.Append("</TcPlcObject>\n");
        return NormalizeLineEndings(xml.ToString());
    }

    public static string RenderApplicationUnitBase(
        string functionBlockName,
        string sourceId,
        Guid twinCatGuid,
        Guid hookGuid,
        string productVersion)
    {
        var declaration =
            $"(* <auto-generated by ETAB Engineering; source-id: {sourceId}; artifact-kind: base-function-block> *)\n" +
            $"FUNCTION_BLOCK {functionBlockName} EXTENDS ETAB.FB_ETAB_ApplicationUnit\n";
        const string implementation =
            "SUPER^();\n" +
            "OnExecuteOperation();\n";
        const string hookDeclaration =
            "METHOD PROTECTED OnExecuteOperation\n" +
            "VAR_INPUT\n" +
            "END_VAR\n";
        const string hookImplementation =
            ";(* Intentionally empty generated extension hook. *)\n";

        var escapedName = SecurityElement.Escape(functionBlockName);
        var escapedVersion = SecurityElement.Escape(productVersion);

        var xml = new StringBuilder();
        xml.Append("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n");
        xml.Append($"<TcPlcObject Version=\"1.1.0.1\" ProductVersion=\"{escapedVersion}\">\n");
        xml.Append($"  <POU Name=\"{escapedName}\" Id=\"{{{twinCatGuid:D}}}\" SpecialFunc=\"None\">\n");
        xml.Append($"    <Declaration><![CDATA[{EscapeCData(declaration)}]]></Declaration>\n");
        xml.Append("    <Implementation>\n");
        xml.Append($"      <ST><![CDATA[{EscapeCData(implementation)}]]></ST>\n");
        xml.Append("    </Implementation>\n");
        xml.Append($"    <Method Name=\"OnExecuteOperation\" Id=\"{{{hookGuid:D}}}\">\n");
        xml.Append($"      <Declaration><![CDATA[{EscapeCData(hookDeclaration)}]]></Declaration>\n");
        xml.Append("      <Implementation>\n");
        xml.Append($"        <ST><![CDATA[{EscapeCData(hookImplementation)}]]></ST>\n");
        xml.Append("      </Implementation>\n");
        xml.Append("    </Method>\n");
        xml.Append("  </POU>\n");
        xml.Append("</TcPlcObject>\n");
        return xml.ToString();
    }

    private static string EscapeCData(string value) =>
        value.Replace("]]>", "]]]]><![CDATA[>", StringComparison.Ordinal);

    private static string NormalizeLineEndings(string value) =>
        value.Replace("\r\n", "\n", StringComparison.Ordinal)
            .Replace('\r', '\n');
}
